name: documentation

# Controls when the workflow will run
on:
  #Allow this workflow to be used in other repositories
  - workflow_call
  #Self-check of readme.md etc.

jobs:
  markdown-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: markdown-lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          debug: true
  yaml-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
