# python-code-quality-action/action.yml
name: Python Code Quality

on:
  workflow_call:
  repository_dispatch:
    types:
      - lint-python

permissions:
  contents: read # git permissions to repo pull/push
  statuses: write # read/write to repo custom statuses and checks

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          pip install pylint
          pip install flake8
          pip install black
      - name: pylint, flake8, and black
        run: |
          set +e  # Disable exit on error temporarily

          # Run pylint
          pylint **/*.py

          exit_status=$?
          # Run flake8
          flake8
          if [ $exit_status -ne 0 ]; then
            exit_status=$?
          fi
          # Run black
          black --diff .
          if [ $exit_status -ne 0 ]; then
            exit_status=$?
          fi
          # Check the exit status of the previous commands
          # Re-enable exit on error
          set -e

          # Exit with the appropriate status
          if [ $exit_status -ne 0 ]; then
            echo "Linting or formatting checks failed"
            exit 1
          fi
