# python-code-quality-action/action.yml
name: Python Code Quality

on:
  workflow_call:
  repository_dispatch:
    types:
      - lint-python

permissions:
  contents: read # git permissions to repo pull/push
  statuses: write # read/write to repo custom statuses and checks

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          pip install pylint
          pip install flake8
          pip install black
          pip install mypy

      - name: Run pylint
        run: pylint ${{ inputs.directory }}

      - name: Run flake8
        run: flake8 ${{ inputs.directory }}

      - name: Run black
        run: black ${{ inputs.directory }} --check

      - name: Run mypy
        run: mypy ${{ inputs.directory }}
