# python-code-quality-action/action.yml
name: Python Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          pip install pylint==2.13.2
          pip install flake8==3.10.0
          pip install black==21.9b0
          pip install mypy==0.910

      - name: Run pylint
        run: pylint ${{ inputs.directory }}

      - name: Run flake8
        run: flake8 ${{ inputs.directory }}

      - name: Run black
        run: black ${{ inputs.directory }} --check

      - name: Run mypy
        run: mypy ${{ inputs.directory }}
